---
title: "Survey data analysis"
author: "Jackie Ouzman"
date: "22/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(readxl)
library(DT)
#install.packages("scales")
library(scales)
```

## Do this a sections first 


```{r import dataset advisor}

#These names are very long perhaps we can make them shorter?

headers <- read_excel("Using soil and plant testing data to better inform nutrient management.xlsx", 
                   sheet = "Data", col_names=FALSE, range = "A1:DO1")
data <- read_excel("Using soil and plant testing data to better inform nutrient management.xlsx", 
                   sheet = "Data", col_names=FALSE, range = "A4:DO74")

names(data) <- headers
#names(data)


```

## subset of data

setting the display names and the order I want them to appear

```{r setting up the region names and order, echo=FALSE}
data <- mutate(data,
             names_display =case_when(
               Q1_region == "SA - Mallee (low rainfall)" ~  "SA - Mallee",
               Q1_region == "SA – Lower EP (medium rainfall)" ~  "SA – Lower EP",
               Q1_region == "SA - Mid North (medium rainfall)" ~  "SA - Mid North",
               Q1_region == "SA - Yorke Peninsula (medium rainfall)" ~  "SA - Yorke Peninsula",
               Q1_region == "SA - Upper EP (low rainfall)" ~  "SA - Upper EP",
               Q1_region == "SA - South East (medium rainfall)" ~  "SA - South East",
               Q1_region == "VIC - Wimmera (medium rainfall)" ~  "VIC - Wimmera",
               Q1_region == "VIC - Mallee (low rainfall)" ~  "VIC - Mallee",
               Q1_region == "VIC - Southern region (high rainfall)" ~  "VIC - Southern region",
               Q1_region == "Other (please specify)" ~  "Other"))
data <- mutate(data, names_display = fct_relevel(names_display, c("SA - Mallee", 
                                       "SA – Lower EP", 
                                       "SA - Mid North", 
                                       "SA - Yorke Peninsula", 
                                       "SA - Upper EP", 
                                       "SA - South East", 
                                       "VIC - Wimmera",
                                       "VIC - Mallee",
                                       "VIC - Southern region",
                                       "Other")))

```

Summary of data 
```{r Q2, echo=FALSE}

Q2 <- group_by(data, names_display) %>% 
  summarise(
    count = n(),
    Ave_Cropped_Area = round(mean(`Q2_Cropped Area`), 0)) %>% 
    arrange(names_display)

head(Q2, 15)

datatable(Q2,  colnames = c( "names", "count", "average cropped area"),
          rownames = FALSE)
          
ggplot(Q2, aes(names_display, Ave_Cropped_Area))+
  geom_col()+
  theme_classic()+
  labs(x= "Regions",
       y = "Cropped area")+
  theme(axis.text.x=element_text(angle=90,hjust=1)) +
  scale_y_continuous(labels =  comma)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
